# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Build 
      run: |
        sudo apt-get install build-essential 
        sudo apt-get install valac
        sudo apt-get install libgtk-3-dev
        sudo apt-get install libgee-0.8-dev
        sudo apt-get install meson
        mkdir build
        cd build
        meson ..
        ninja
        # TODO: decide what happend with this
        #       If this is meant as a test for linking a binary against the library, this is
        #       already tested by building the unittests. If you want to keep it, i'd recommend to
        #       create another meson executable section.
        # valac --pkg gtk+-3.0 --pkg gee-0.8 Caroline.vapi ../Sample.vala -X Caroline.so -X -I. -o demo
    - name: Tests 
      run: |
        sudo apt-get install xvfb
        cd build
        xvfb-run ./caroline-vala
